version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email) | sed 's,https://,,g'
      - TAG="$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)"
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$TAG      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$TAG
      - export secretExists=$(aws secretsmanager describe-secret --secret-id ImageTag)
      -  |
         if [ -z "$secretExists" ]; then 
         aws secretsmanager create-secret --name ImageTag --secret-string $TAG --description "Current tag"; else 
         aws secretsmanager put-secret-value --secret-id ImageTag --secret-string $TAG; 
         fi
      -  echo $(aws secretsmanager get-secret-value --secret-id ImageTag --query SecretString --output text) > tagValue.txt
artifacts:
   files:
    - tagValue.txt    
